In [1]:
from google.colab import files

uploaded = files.upload()

Saving CIFPS - DATASET B.zip to CIFPS - DATASET B.zip

In [2]:
import zipfile

zip_path = "CIFPS - DATASET B.zip"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/datasetB')

print("Extraction Complete!")

Extraction Complete!

In [3]:
import os

for root, dirs, files in os.walk('/content/datasetB'):
    print(f"\n📁 Folder: {root}")

    for file in files:
        print("   📄", file)

📁 Folder: /content/datasetB

📁 Folder: /content/datasetB/Failure-Dataset-OpenStack-main
   📄 LICENSE
   📄 README.md

📁 Folder: /content/datasetB/Failure-Dataset-OpenStack-main/STO
   📄 Failure_Labels.txt
   📄 SEQ.tsv
   📄 LCS_with_VMM.tsv

📁 Folder: /content/datasetB/Failure-Dataset-OpenStack-main/NET
   📄 Failure_Labels.txt
   📄 SEQ.tsv
   📄 LCS_with_VMM.tsv

📁 Folder: /content/datasetB/Failure-Dataset-OpenStack-main/DEPL
   📄 Failure_Labels.txt
   📄 SEQ.tsv
   📄 LCS_with_VMM.tsv

In [4]:
readme_path = "/content/datasetB/Failure-Dataset-OpenStack-main/README.md"

with open(readme_path, "r", encoding="utf-8") as f:
    content = f.read()

print(content[:10000])

# Failure-Dataset-OpenStack

This failure dataset contains information on the events collected in the **OpenStack** cloud computing platform during three different campaigns of **fault-injection** experiments performed with three different workloads (**DEPL**, **NET**, and **STO**).

The dataset contains three folders referring to the three different fault-injection campaigns (one per each workload).
In every folder, you can find:
* **SEQ.tsv**: a matrix with *N* rows and *d* columns containing the events collected during the fault-injection experiments. *N* is the number of fault-injection experiments, *d* represents the number of different event types (unique events).
* **LCS_with_VMM.tsv**: a matrix with *N* rows and *2d* columns containing the anomalies identified by the *LCS with VMM* approach during the fault-injection experiments. *N* is the number of fault-injection experiments, *d* represents the number of different event types (unique events). The first *d* columns (*1* to *d*) represent the number of spurious anomalies, the last d columns (*d+1* to *2d*) represents the number of missing anomalies.
* **Failure_Labels.txt**: a file containing the label class associated with every fault-injection experiment. The class label is expressed by a number.

The number *N* of experiments and the number *d* of events depend on the workload used during the fault-injection experiments. Therefore, the matrix dimension in the *tsv* files change in every folder.
We invite the reader to find further information on the data representation, the workloads, the anomaly types, and the failure classes by reading the paper [Enhancing the Analysis of Software Failuresin Cloud Computing Systems with Deep Learning](https://doi.org/10.1016/j.jss.2021.111043) accepted at the Journal of Systems and Software:

```
@article{cotroneo2021enhancing,
  title={Enhancing the analysis of software failures in cloud computing systems with deep learning},
  author={Cotroneo, Domenico and De Simone, Luigi and Liguori, Pietro and Natella, Roberto},
  journal={Journal of Systems and Software},
  volume={181},
  pages={111043},
  year={2021},
  publisher={Elsevier}
}
```

The slide presentation of the paper is available on [slideshare](https://www.slideshare.net/PietroLiguori4/enhancing-the-analysis-of-software-failures-in-cloud-computing-systems-with-deep-learning), while you can find the video presentation of the paper on [Youtube](https://www.youtube.com/watch?v=sQyol2aH-u0&list=PLhBMpvlFe-cHGnN9-9R5h2FWqjbBdyjA0&index=3&t=2s).

## Failure Classes
In our fault-injection experiments, we found different failure modes. We associated to each failure-mode a numeric value (**Failure Label**).

### DEPL
In the fault-injection campaing performed with the DEPL workload, the experiments experienced *6* different types of failures:

* **Failure Label 1**: *Instance Failure*
* **Failure Label 2**: *Volume Failure*
* **Failure Label 3**: *SSH Failure*
* **Failure Label 4**: *Cleanup Failure*
* **Failure Label 5**: *Network Failure*
* **Failure Label 6**: *No Failure*

### NET
In the fault-injection campaign performed with the NET workload, the experiments experienced *4* different types of failures:

* **Failure Label 1**: *Instance Failure*
* **Failure Label 2**: *Network Failure*
* **Failure Label 3**: *SSH Failure*
* **Failure Label 4**: *No Failure*


### STO
In the fault-injection campaign performed with the DEPL workload, the experiments experienced *4* different types of failures:

* **Failure Label 1**: *Volume Failure*
* **Failure Label 2**: *Instance Failure*
* **Failure Label 3**: *Cleanup Failure*
* **Failure Label 4**: *No Failure*

In [5]:
import pandas as pd

depl_seq = pd.read_csv(
    "/content/datasetB/Failure-Dataset-OpenStack-main/DEPL/SEQ.tsv",
    sep="\t"
)

print(depl_seq.shape)

depl_seq.head()

(1076, 104)

,cinderclient_DELETE_202,cinderclient_DELETE_400,cinderclient_DELETE_500,cinderclient_GET_200,cinderclient_GET_400,cinderclient_GET_404,cinderclient_GET_500,cinderclient_POST_200,cinderclient_POST_202,cinderclient_POST_400,...,q-plugin_get_ports,q-plugin_release_dhcp_port,q-plugin_update_device_list,q-plugin_update_device_list_ERROR,scheduler_delete_instance_info,scheduler_delete_instance_info_ERROR,scheduler_select_destinations,scheduler_select_destinations_ERROR,scheduler_update_instance_info,scheduler_update_instance_info_ERROR
0,1,0,0,10,0,1,0,1,5,0,...,24,2,15,0,1,0,1,0,1,0
1,1,0,0,10,0,1,0,1,5,0,...,26,2,15,0,1,0,1,0,1,0
2,1,0,0,10,0,1,0,1,5,0,...,28,2,15,0,1,0,1,0,1,0
3,1,0,0,10,0,1,0,1,5,0,...,26,3,18,0,1,0,1,0,1,0
4,1,0,0,10,0,1,0,1,5,0,...,28,3,18,0,1,0,1,0,1,0

In [6]:
labels = pd.read_csv(
    "/content/datasetB/Failure-Dataset-OpenStack-main/DEPL/Failure_Labels.txt",
    header=None
)

print(labels.shape)

labels.head()

(1076, 1)

   0
0  6
1  6
2  6
3  6
4  6

In [7]:
print(labels[0].value_counts().sort_index())

0
1    224
2    151
3     41
4     69
5     52
6    539
Name: count, dtype: int64

In [8]:
depl_seq.isnull().sum().sum()

np.int64(0)

In [9]:
net_seq = pd.read_csv(
    "/content/datasetB/Failure-Dataset-OpenStack-main/NET/SEQ.tsv",
    sep="\t"
)

sto_seq = pd.read_csv(
    "/content/datasetB/Failure-Dataset-OpenStack-main/STO/SEQ.tsv",
    sep="\t"
)

print("NET Shape:", net_seq.shape)
print("STO Shape:", sto_seq.shape)

NET Shape: (561, 59)
STO Shape: (901, 75)

In [10]:
net_labels = pd.read_csv(
    "/content/datasetB/Failure-Dataset-OpenStack-main/NET/Failure_Labels.txt",
    header=None
)

sto_labels = pd.read_csv(
    "/content/datasetB/Failure-Dataset-OpenStack-main/STO/Failure_Labels.txt",
    header=None
)

print("DEPL")
print(labels[0].value_counts().sort_index())

print("\nNET")
print(net_labels[0].value_counts().sort_index())

print("\nSTO")
print(sto_labels[0].value_counts().sort_index())

DEPL
0
1    224
2    151
3     41
4     69
5     52
6    539
Name: count, dtype: int64

NET
0
1     56
2    195
3     11
4    299
Name: count, dtype: int64

STO
0
1     38
2    320
3    157
4    386
Name: count, dtype: int64